const NEXT_QUESTION = 'NEXT_QUESTION'
const RECORD_ITEM_ANSWER = 'RECORD_ITEM_ANSWER'
const RECORD_ANSWER_TIME = 'RECORD_ANSWER_TIME'
const INIT_QUESTION = 'INIT_QUESTION'

export default {
  NEXT_QUESTION,
  RECORD_ITEM_ANSWER,
  RECORD_ANSWER_TIME,
  INIT_QUESTION
}
